# Generated by Django 3.0.7 on 2020-07-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200626_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='movierater/images/default.png', upload_to='movierater/images/'),
        ),
    ]
