# Generated by Django 3.0.7 on 2020-07-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='api/images/default.png', upload_to='api/images/'),
        ),
    ]
